#pragma once

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define GAME_HEIGHT 550

#define TILE_MAP_COLLUMNS 16
#define TILE_MAP_ROWS 11
#define SNAKE_BODY_TOTAL 24
#define APPLE_BASE_POINTS 1
#define LIVES 3
#define START_MOVEMENT_DELAY 0.5f
#define MIN_MOVEMENT_DELAY 0.1f
#define MOVEMENT_STEP ((float)((START_MOVEMENT_DELAY-MIN_MOVEMENT_DELAY)/(SNAKE_BODY_TOTAL/2)))
#define MAX_SCORE 9999